#
# DigitalOcean App Platform Configuration
# This file configures deployment to DigitalOcean App Platform
#
name: whatsapp-lims-app

services:
- name: whatsapp-lims-api
  source_dir: NodeBackend
  github:
    repo: anprohealthtech-lab/WHATSAPP-PERSISTENT
    branch: master
  build_command: |
    npm install
    npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-s  # 512MB RAM, 0.5 vCPU
  http_port: 3001
  
  envs:
  - key: NODE_ENV
    value: production
    
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    
  - key: SESSION_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    
  - key: PORT
    value: "3001"
    
  - key: MAX_FILE_SIZE
    value: "10485760"
    
  - key: ALLOWED_FILE_TYPES
    value: "pdf,jpg,jpeg,png"

  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 10
    failure_threshold: 3

# Optional: Static site service if you want to serve frontend separately
# - name: whatsapp-lims-frontend  
#   source_dir: /NodeBackend
#   build_command: |
#     npm ci
#     npm run build:frontend
#   output_dir: /dist
#   type: STATIC_SITE

databases:
- name: whatsapp-lims-db
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb
  num_nodes: 1

# Optional: Add Redis for session storage in production
# - name: whatsapp-lims-redis
#   engine: REDIS
#   version: "7"
#   size: db-s-1vcpu-1gb

# Storage for persistent files (consider for uploads)
# volumes:
# - name: uploads-storage
#   size: 5GiB
#   mount_path: /app/uploads

# Domain configuration
domains:
- domain: your-domain.com
  type: PRIMARY
  wildcard: false
  certificate:
    type: LETS_ENCRYPT